spring:
  jpa:
      show_sql: true
      format_sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServer2008Dialect
          format_sql: true
          use_sql_comments: true

  datasource:
      url: jdbc:sqlserver://192.168.0.27:1433;databaseName=FILELOGDB
      username: file
      password: 1234

      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      validationQuery: SELECT 1
      validationInterval: 1000
      testOnBorrow: true
